# 服务 ID
custom_push_mqtt:
  description: "自定义mqtt推送服务"
  # 服务接受的字段
  fields:
    # MQTT 主题
    topic:
      required: false
      example: "P/0/center/q24"
      description: "请输入 MQTT 主题"
      selector:
        text:
    # 发送的数据
    payload:
      required: true
      example: "-"
      description: "请输入 JSON 格式的数据"
      selector:
        text:
    n_id:
      required: false
      example: "-"
      description: "请输入 通知id 留空为 topic"
      selector:
        text:  
        
log_query:
  # 服务接受的字段
  description: "查询日志记录"
  fields:
    # 发送的数据
    place_id:
      required: true
      example: "-"
      description: "输入场所id"
      selector:
        text: 
    start:
      required: false
      example: "-"
      description: "开始位置"
      selector:
        text:  
    max:
      required: false
      example: "-"
      description: "每页显示位置"
      selector:
        text:    
    n_id:
      required: false
      example: "-"
      description: "请输入 通知id 留空为 topic"
      selector:
        text:

get_backupconfig:
  description: "获取备份配置"
  fields:
    # 备份配置名称
    name:
      required: true
      example: "username"
      description: "请输入用户"
      selector:
        text:
    password:
      required: true
      example: "123456"
      description: "请输入密码"
      selector:
        text: 
    url:
      required: False
      example: "xxx.xxx.xxx.com"
      description: "请输入url"
      selector:
        text:
    manufacturer:
       required: False
       example: "Xxxxx"
       description: "请输入厂商"
       selector:
         text:
    envKey:
      required: true
      example: "123456"
      description: "请输envKey"
      selector:
        text:
          
          