# 服务 ID
custom_push_mqtt:
  description: "自定义mqtt推送服务"
  # 服务接受的字段
  fields:
    # MQTT 主题
    topic:
      required: false
      example: "P/0/center/q24"
      selector:
        text:
          multiline: false
          placeholder: "请输入 MQTT 主题"

    # 发送的数据
    data:
      required: true
      example: "-"
      selector:
        json:
          multiline: false
          placeholder: "请输入 JSON 格式的数据"
    n_id:
      required: false
      example: "-"
      selector:
        text:
          multiline: false
          placeholder: "请输入 通知id 留空为 topic"
log_query:
  # 服务接受的字段
  description: "查询日志记录"
  fields:
    # 发送的数据
    place_id:
      required: true
      example: "-"
      selector:
        text:
          multiline: false
          placeholder: "输入场所id"
    start:
      required: false
      example: "-"
      selector:
        text:
          multiline: false
          placeholder: "开始位置"
    max:
      required: false
      example: "-"
      selector:
        text:
          multiline: false
          placeholder: "每页显示位置"
    place_id:
      required: false
      example: "-"
      selector:
        text:
          multiline: false
          placeholder: "请输入 JSON 格式的数据"
    n_id:
      required: false
      example: "-"
      selector:
        text:
          multiline: false
          placeholder: "请输入 通知id 留空为 topic"

get_backupconfig:
  description: "获取备份配置"
  fields:
    # 备份配置名称
    name:
      required: true
      example: "username"
      selector:
        text:
          multiline: false
          placeholder: "请输入用户"

    password:
      required: true
      example: "123456"
      selector:
        text:
          multiline: false
          placeholder: "请输入密码"
    url:
      required: False
      example: "xxx.xxx.xxx.com"
      selector:
        text:
          multiline: false
          placeholder: "请输入url"

    manufacturer:
       required: False
       example: "Xxxxx"
       selector:
         text:
           multiline: false
           placeholder: "请输入厂商"
    
    envKey:
      required: true
      example: "123456"
      selector:
        text:
          multiline: false
          placeholder: "请输envKey"
